# Dockerfile for wurth_circulating_tumor
# Würth, R., Donato, E., Michel, L.L. et al. Circulating tumor cell plasticity determines breast cancer therapy resistance via neuregulin 1–HER3 signaling. Nat Cancer 6, 67–85 (2025). https://doi.org/10.1038/s43018-024-00882-2

